min_version = "2026.4.18" # required for [deps] (renamed from [prepare])

[tools]
"npm:@nubjs/nub" = "0.4.12"
node = "lts"
jq = "latest"
vp = "latest"
hk = "latest"

[task_config]
dir = "{{ config_root }}"

[env]
'_'.path = { path = "./node_modules/.bin" }
STORYBOOK_ENABLE_CRASH_REPORTS = 1
HK_PKL_BACKEND = "pklr"
HK_MISE = 1

[deps.nub]
auto = true

[shell_alias]
mr = "mise run"
